package com.cubic.service;

public interface QueryConstant {
	String GET_ALL_VEHICLE = "GET_ALL_VEHICLE";
	String SEARCH_BY_VEHICLE_NAME = "SEARCH_BY_VEHICLE_NAME";
	String SEARCH_BY_VEHICLE_MAKE = "SEARCH_BY_VEHICLE_MAKE";
	String QUERY_SEARCH_BY_VEHICLE_VIN = "QUERY_SEARCH_BY_VEHICLE_VIN";
	String ROUTE_SEARCH_BY_ROUTENAME = "ROUTE_SEARCH_BY_ROUTENAME";
	String ROUTE_GETALL_ROUTE = "ROUTE_GETALL_ROUTE";
	String ROUTE_SEARCH_BY_CITY = "ROUTE_SEARCH_BY_CITY";
	String ROUTE_SEARCH_BY_END_DEST = "ROUTE_SEARCH_BY_END_DEST";

}
